// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/local/entities/pokemon_entity.dart';
import 'data/local/entities/pokemon_interaction_entity.dart';
import 'data/local/entities/received_achievement_entity.dart';
import 'data/local/entities/user_profile_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6582625366291580358),
    name: 'PokemonEntity',
    lastPropertyId: const obx_int.IdUid(25, 6797638106672661769),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7074926002719553260),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6700320584546828828),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3525611347977465317),
        name: 'generation',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1555627733291799928),
        name: 'bst',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 565589447382310112),
        name: 'hiddenAbility',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3900434122476011710),
        name: 'ability1',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5666962775994549435),
        name: 'ability2',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6905406995687784050),
        name: 'noOfForms',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 9155952350452833934),
        name: 'types',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 661355321079310776),
        name: 'evolutionTreeSize',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8643433998123449656),
        name: 'evolutionItem',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 2793786732961899732),
        name: 'usableEvolutionItems',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8475628575919465901),
        name: 'stageOfEvolution',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 9208425719573270251),
        name: 'cry',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 2003972994764883616),
        name: 'hasMega',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 3785886188780414414),
        name: 'hasGmax',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 8226811958251422823),
        name: 'isBaby',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 2663670664903511490),
        name: 'isLegendary',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 6202145939562420574),
        name: 'isMythical',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 5931471156637939825),
        name: 'isStarter',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 8052868021546154084),
        name: 'isPseudo',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 149737774177849648),
        name: 'isMega',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 2132630234330637963),
        name: 'isGmax',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 851660279391860087),
        name: 'speciesID',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 6797638106672661769),
        name: 'variantIDs',
        type: 27,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 1716144295224908794),
    name: 'PokemonInteractionEntity',
    lastPropertyId: const obx_int.IdUid(6, 7925408365907082281),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7894767157480074029),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4154479916835810041),
        name: 'pokemonId',
        type: 6,
        flags: 40,
        indexId: const obx_int.IdUid(1, 461376106243726858),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9176130731351788170),
        name: 'couldNotGuess',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7965345097619730484),
        name: 'catchFailed',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4262640931040803166),
        name: 'caughtNormal',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7925408365907082281),
        name: 'caughtShiny',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 4005050420529562430),
    name: 'ReceivedAchievementEntity',
    lastPropertyId: const obx_int.IdUid(3, 459489525629957904),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1212873070786711827),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5192474739877678476),
        name: 'achievementId',
        type: 6,
        flags: 40,
        indexId: const obx_int.IdUid(2, 3937881487826277696),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 459489525629957904),
        name: 'receivedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 3518277617784564902),
    name: 'UserProfileEntity',
    lastPropertyId: const obx_int.IdUid(6, 129024250986088076),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8711083237420585593),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4297635111672712403),
        name: 'username',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8433162985723476233),
        name: 'firstCatchPokemonId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7204529376998605494),
        name: 'userColorString',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3904586018294507240),
        name: 'points',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 129024250986088076),
        name: 'level',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 3518277617784564902),
    lastIndexId: const obx_int.IdUid(2, 3937881487826277696),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    PokemonEntity: obx_int.EntityDefinition<PokemonEntity>(
      model: _entities[0],
      toOneRelations: (PokemonEntity object) => [],
      toManyRelations: (PokemonEntity object) => {},
      getId: (PokemonEntity object) => object.id,
      setId: (PokemonEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PokemonEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final hiddenAbilityOffset = object.hiddenAbility == null
            ? null
            : fbb.writeString(object.hiddenAbility!);
        final ability1Offset = object.ability1 == null
            ? null
            : fbb.writeString(object.ability1!);
        final ability2Offset = object.ability2 == null
            ? null
            : fbb.writeString(object.ability2!);
        final typesOffset = fbb.writeList(
          object.types.map(fbb.writeString).toList(growable: false),
        );
        final evolutionItemOffset = object.evolutionItem == null
            ? null
            : fbb.writeString(object.evolutionItem!);
        final usableEvolutionItemsOffset = fbb.writeList(
          object.usableEvolutionItems
              .map(fbb.writeString)
              .toList(growable: false),
        );
        final cryOffset = fbb.writeString(object.cry);
        final variantIDsOffset = fbb.writeListInt64(object.variantIDs);
        fbb.startTable(26);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.generation);
        fbb.addInt64(3, object.bst);
        fbb.addOffset(4, hiddenAbilityOffset);
        fbb.addOffset(5, ability1Offset);
        fbb.addOffset(6, ability2Offset);
        fbb.addInt64(7, object.noOfForms);
        fbb.addOffset(8, typesOffset);
        fbb.addInt64(9, object.evolutionTreeSize);
        fbb.addOffset(10, evolutionItemOffset);
        fbb.addOffset(11, usableEvolutionItemsOffset);
        fbb.addInt64(12, object.stageOfEvolution);
        fbb.addOffset(13, cryOffset);
        fbb.addBool(14, object.hasMega);
        fbb.addBool(15, object.hasGmax);
        fbb.addBool(16, object.isBaby);
        fbb.addBool(17, object.isLegendary);
        fbb.addBool(18, object.isMythical);
        fbb.addBool(19, object.isStarter);
        fbb.addBool(20, object.isPseudo);
        fbb.addBool(21, object.isMega);
        fbb.addBool(22, object.isGmax);
        fbb.addInt64(23, object.speciesID);
        fbb.addOffset(24, variantIDsOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final generationParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final bstParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final hiddenAbilityParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final ability1Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final ability2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final noOfFormsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final typesParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 20, []);
        final evolutionTreeSizeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final evolutionItemParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final usableEvolutionItemsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 26, []);
        final stageOfEvolutionParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final cryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final hasMegaParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          32,
          false,
        );
        final hasGmaxParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          34,
          false,
        );
        final isBabyParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          36,
          false,
        );
        final isLegendaryParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          38,
          false,
        );
        final isMythicalParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          40,
          false,
        );
        final isStarterParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          42,
          false,
        );
        final isPseudoParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          44,
          false,
        );
        final isMegaParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          46,
          false,
        );
        final isGmaxParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          48,
          false,
        );
        final speciesIDParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          50,
          0,
        );
        final variantIDsParam = const fb.ListReader<int>(
          fb.Int64Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 52, []);
        final object = PokemonEntity(
          id: idParam,
          name: nameParam,
          generation: generationParam,
          bst: bstParam,
          hiddenAbility: hiddenAbilityParam,
          ability1: ability1Param,
          ability2: ability2Param,
          noOfForms: noOfFormsParam,
          types: typesParam,
          evolutionTreeSize: evolutionTreeSizeParam,
          evolutionItem: evolutionItemParam,
          usableEvolutionItems: usableEvolutionItemsParam,
          stageOfEvolution: stageOfEvolutionParam,
          cry: cryParam,
          hasMega: hasMegaParam,
          hasGmax: hasGmaxParam,
          isBaby: isBabyParam,
          isLegendary: isLegendaryParam,
          isMythical: isMythicalParam,
          isStarter: isStarterParam,
          isPseudo: isPseudoParam,
          isMega: isMegaParam,
          isGmax: isGmaxParam,
          speciesID: speciesIDParam,
          variantIDs: variantIDsParam,
        );

        return object;
      },
    ),
    PokemonInteractionEntity:
        obx_int.EntityDefinition<PokemonInteractionEntity>(
          model: _entities[1],
          toOneRelations: (PokemonInteractionEntity object) => [],
          toManyRelations: (PokemonInteractionEntity object) => {},
          getId: (PokemonInteractionEntity object) => object.id,
          setId: (PokemonInteractionEntity object, int id) {
            object.id = id;
          },
          objectToFB: (PokemonInteractionEntity object, fb.Builder fbb) {
            fbb.startTable(7);
            fbb.addInt64(0, object.id);
            fbb.addInt64(1, object.pokemonId);
            fbb.addInt64(2, object.couldNotGuess);
            fbb.addInt64(3, object.catchFailed);
            fbb.addInt64(4, object.caughtNormal);
            fbb.addInt64(5, object.caughtShiny);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final idParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              4,
              0,
            );
            final pokemonIdParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              6,
              0,
            );
            final couldNotGuessParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              8,
              0,
            );
            final catchFailedParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              10,
              0,
            );
            final caughtNormalParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              12,
              0,
            );
            final caughtShinyParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              14,
              0,
            );
            final object = PokemonInteractionEntity(
              id: idParam,
              pokemonId: pokemonIdParam,
              couldNotGuess: couldNotGuessParam,
              catchFailed: catchFailedParam,
              caughtNormal: caughtNormalParam,
              caughtShiny: caughtShinyParam,
            );

            return object;
          },
        ),
    ReceivedAchievementEntity:
        obx_int.EntityDefinition<ReceivedAchievementEntity>(
          model: _entities[2],
          toOneRelations: (ReceivedAchievementEntity object) => [],
          toManyRelations: (ReceivedAchievementEntity object) => {},
          getId: (ReceivedAchievementEntity object) => object.id,
          setId: (ReceivedAchievementEntity object, int id) {
            object.id = id;
          },
          objectToFB: (ReceivedAchievementEntity object, fb.Builder fbb) {
            fbb.startTable(4);
            fbb.addInt64(0, object.id);
            fbb.addInt64(1, object.achievementId);
            fbb.addInt64(2, object.receivedAt.millisecondsSinceEpoch);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final idParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              4,
              0,
            );
            final achievementIdParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              6,
              0,
            );
            final receivedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
            );
            final object = ReceivedAchievementEntity(
              id: idParam,
              achievementId: achievementIdParam,
              receivedAt: receivedAtParam,
            );

            return object;
          },
        ),
    UserProfileEntity: obx_int.EntityDefinition<UserProfileEntity>(
      model: _entities[3],
      toOneRelations: (UserProfileEntity object) => [],
      toManyRelations: (UserProfileEntity object) => {},
      getId: (UserProfileEntity object) => object.id,
      setId: (UserProfileEntity object, int id) {
        object.id = id;
      },
      objectToFB: (UserProfileEntity object, fb.Builder fbb) {
        final usernameOffset = fbb.writeString(object.username);
        final userColorStringOffset = object.userColorString == null
            ? null
            : fbb.writeString(object.userColorString!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, usernameOffset);
        fbb.addInt64(2, object.firstCatchPokemonId);
        fbb.addOffset(3, userColorStringOffset);
        fbb.addInt64(4, object.points);
        fbb.addInt64(5, object.level);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final usernameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final firstCatchPokemonIdParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 8);
        final userColorStringParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final pointsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final levelParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = UserProfileEntity(
          id: idParam,
          username: usernameParam,
          firstCatchPokemonId: firstCatchPokemonIdParam,
          userColorString: userColorStringParam,
          points: pointsParam,
          level: levelParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [PokemonEntity] entity fields to define ObjectBox queries.
class PokemonEntity_ {
  /// See [PokemonEntity.id].
  static final id = obx.QueryIntegerProperty<PokemonEntity>(
    _entities[0].properties[0],
  );

  /// See [PokemonEntity.name].
  static final name = obx.QueryStringProperty<PokemonEntity>(
    _entities[0].properties[1],
  );

  /// See [PokemonEntity.generation].
  static final generation = obx.QueryIntegerProperty<PokemonEntity>(
    _entities[0].properties[2],
  );

  /// See [PokemonEntity.bst].
  static final bst = obx.QueryIntegerProperty<PokemonEntity>(
    _entities[0].properties[3],
  );

  /// See [PokemonEntity.hiddenAbility].
  static final hiddenAbility = obx.QueryStringProperty<PokemonEntity>(
    _entities[0].properties[4],
  );

  /// See [PokemonEntity.ability1].
  static final ability1 = obx.QueryStringProperty<PokemonEntity>(
    _entities[0].properties[5],
  );

  /// See [PokemonEntity.ability2].
  static final ability2 = obx.QueryStringProperty<PokemonEntity>(
    _entities[0].properties[6],
  );

  /// See [PokemonEntity.noOfForms].
  static final noOfForms = obx.QueryIntegerProperty<PokemonEntity>(
    _entities[0].properties[7],
  );

  /// See [PokemonEntity.types].
  static final types = obx.QueryStringVectorProperty<PokemonEntity>(
    _entities[0].properties[8],
  );

  /// See [PokemonEntity.evolutionTreeSize].
  static final evolutionTreeSize = obx.QueryIntegerProperty<PokemonEntity>(
    _entities[0].properties[9],
  );

  /// See [PokemonEntity.evolutionItem].
  static final evolutionItem = obx.QueryStringProperty<PokemonEntity>(
    _entities[0].properties[10],
  );

  /// See [PokemonEntity.usableEvolutionItems].
  static final usableEvolutionItems =
      obx.QueryStringVectorProperty<PokemonEntity>(_entities[0].properties[11]);

  /// See [PokemonEntity.stageOfEvolution].
  static final stageOfEvolution = obx.QueryIntegerProperty<PokemonEntity>(
    _entities[0].properties[12],
  );

  /// See [PokemonEntity.cry].
  static final cry = obx.QueryStringProperty<PokemonEntity>(
    _entities[0].properties[13],
  );

  /// See [PokemonEntity.hasMega].
  static final hasMega = obx.QueryBooleanProperty<PokemonEntity>(
    _entities[0].properties[14],
  );

  /// See [PokemonEntity.hasGmax].
  static final hasGmax = obx.QueryBooleanProperty<PokemonEntity>(
    _entities[0].properties[15],
  );

  /// See [PokemonEntity.isBaby].
  static final isBaby = obx.QueryBooleanProperty<PokemonEntity>(
    _entities[0].properties[16],
  );

  /// See [PokemonEntity.isLegendary].
  static final isLegendary = obx.QueryBooleanProperty<PokemonEntity>(
    _entities[0].properties[17],
  );

  /// See [PokemonEntity.isMythical].
  static final isMythical = obx.QueryBooleanProperty<PokemonEntity>(
    _entities[0].properties[18],
  );

  /// See [PokemonEntity.isStarter].
  static final isStarter = obx.QueryBooleanProperty<PokemonEntity>(
    _entities[0].properties[19],
  );

  /// See [PokemonEntity.isPseudo].
  static final isPseudo = obx.QueryBooleanProperty<PokemonEntity>(
    _entities[0].properties[20],
  );

  /// See [PokemonEntity.isMega].
  static final isMega = obx.QueryBooleanProperty<PokemonEntity>(
    _entities[0].properties[21],
  );

  /// See [PokemonEntity.isGmax].
  static final isGmax = obx.QueryBooleanProperty<PokemonEntity>(
    _entities[0].properties[22],
  );

  /// See [PokemonEntity.speciesID].
  static final speciesID = obx.QueryIntegerProperty<PokemonEntity>(
    _entities[0].properties[23],
  );

  /// See [PokemonEntity.variantIDs].
  static final variantIDs = obx.QueryIntegerVectorProperty<PokemonEntity>(
    _entities[0].properties[24],
  );
}

/// [PokemonInteractionEntity] entity fields to define ObjectBox queries.
class PokemonInteractionEntity_ {
  /// See [PokemonInteractionEntity.id].
  static final id = obx.QueryIntegerProperty<PokemonInteractionEntity>(
    _entities[1].properties[0],
  );

  /// See [PokemonInteractionEntity.pokemonId].
  static final pokemonId = obx.QueryIntegerProperty<PokemonInteractionEntity>(
    _entities[1].properties[1],
  );

  /// See [PokemonInteractionEntity.couldNotGuess].
  static final couldNotGuess =
      obx.QueryIntegerProperty<PokemonInteractionEntity>(
        _entities[1].properties[2],
      );

  /// See [PokemonInteractionEntity.catchFailed].
  static final catchFailed = obx.QueryIntegerProperty<PokemonInteractionEntity>(
    _entities[1].properties[3],
  );

  /// See [PokemonInteractionEntity.caughtNormal].
  static final caughtNormal =
      obx.QueryIntegerProperty<PokemonInteractionEntity>(
        _entities[1].properties[4],
      );

  /// See [PokemonInteractionEntity.caughtShiny].
  static final caughtShiny = obx.QueryIntegerProperty<PokemonInteractionEntity>(
    _entities[1].properties[5],
  );
}

/// [ReceivedAchievementEntity] entity fields to define ObjectBox queries.
class ReceivedAchievementEntity_ {
  /// See [ReceivedAchievementEntity.id].
  static final id = obx.QueryIntegerProperty<ReceivedAchievementEntity>(
    _entities[2].properties[0],
  );

  /// See [ReceivedAchievementEntity.achievementId].
  static final achievementId =
      obx.QueryIntegerProperty<ReceivedAchievementEntity>(
        _entities[2].properties[1],
      );

  /// See [ReceivedAchievementEntity.receivedAt].
  static final receivedAt = obx.QueryDateProperty<ReceivedAchievementEntity>(
    _entities[2].properties[2],
  );
}

/// [UserProfileEntity] entity fields to define ObjectBox queries.
class UserProfileEntity_ {
  /// See [UserProfileEntity.id].
  static final id = obx.QueryIntegerProperty<UserProfileEntity>(
    _entities[3].properties[0],
  );

  /// See [UserProfileEntity.username].
  static final username = obx.QueryStringProperty<UserProfileEntity>(
    _entities[3].properties[1],
  );

  /// See [UserProfileEntity.firstCatchPokemonId].
  static final firstCatchPokemonId =
      obx.QueryIntegerProperty<UserProfileEntity>(_entities[3].properties[2]);

  /// See [UserProfileEntity.userColorString].
  static final userColorString = obx.QueryStringProperty<UserProfileEntity>(
    _entities[3].properties[3],
  );

  /// See [UserProfileEntity.points].
  static final points = obx.QueryIntegerProperty<UserProfileEntity>(
    _entities[3].properties[4],
  );

  /// See [UserProfileEntity.level].
  static final level = obx.QueryIntegerProperty<UserProfileEntity>(
    _entities[3].properties[5],
  );
}
